### ISSUE TITLE
Binding to Application Context

### ISSUE THREAD

**Issue by CoreyBehrends** [zapodot/hystrix-dropwizard-bundle#2]
When I bind to an app context using:

configBootstrap.addBundle(HystrixBundle.builder()
                                            .withApplicationStreamPath("/my-path")
                                            .disableStreamServletInAdminContext()
                                            .disableMetricsPublisher()
                                            .build()
                                            );

The context will not return the hystrix metrics, it just spins as though something is blocking.  If I run with default configs it responds as expected on the admin interface.

Any suggestions?

**Comment by zapodot** [comment]
Hi @CoreyBehrends and thanks for reporting back. The Hystrix stream servlet deliveres metrics as a stream of events. When you open it directly in a web-browser it seems to block. Have you tried streaming the data to the Hystrix dasboard (see https://github.com/Netflix/Hystrix/tree/master/hystrix-dashboard) ?

**Comment by CoreyBehrends** [comment]
You are correct, thanks for the help!
